import Footer from '../../components/footer/Footer'
import Navbar from '../../components/navbar/Navbar'
import './app.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Free Chat App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {children}
       
        </body>
        
    </html>
  )
}
